jobs:
  include:
    - stage: "Test"
      name: "Use custom image 2305-image3"
      vm:
        use:
          name: 01-org-images-t34

    - stage: "Test"
      name: "Use custom image 2305-image4"
      vm:
        use:
          name: 01-org-images-t36
